version: "3.8"

services:
  rag-engine:
    build: ./rag_engine
    container_name: rag-engine
    volumes:
      - ./faiss_data:/app/faiss_data # ホストのFAISSデータをマウント
      - ./docs:/app/docs # RAG読み込み用のドキュメントフォルダをマウント
    ports:
      - "5001:5001"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - llm-net
    depends_on:
      ollama:
        condition: service_healthy
  ollama:
    build:
      context: ollama
      dockerfile: Dockerfile
    image: ollama-custom-gpu
    container_name: ollama-gpu
    ports:
      - "11434:11434"
    networks:
      - llm-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ./ollama/models:/import_models
      - ollama_data:/root/.ollama
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/api/tags" ]
      interval: 10s
      timeout: 5s
      retries: 5

  openwebui:
    build:
      context: openwebui
      dockerfile: Dockerfile
    image: openwebui-gpu
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - BACKEND_API_URL=http://ollama:11434
      - OPENAI_API_BASE_URL=http://rag-engine:5001/v1
      - WEBUI_AUTH=False
    networks:
      - llm-net
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  open-webui-data:
  ollama_data:


networks:
  llm-net:
    driver: bridge
